# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_group', models.CharField(max_length=64)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('job_group', models.CharField(max_length=64)),
                ('hours_worked', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
